server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    listen 443 quic;
    listen [::]:443 quic;
    http3 on;
    add_header Alt-Svc 'h3=":443"; ma=86400';

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    server_name www.example.com;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        root /var/www/example;
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(api|docs|openapi) {
        proxy_pass http://localhost:3000;
    }
}
